//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MyPoinNew_CoreGateway.MyPoinCore {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="service2Soap", Namespace="http://tempuri.org/")]
    public partial class service2 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckPoinOperationCompleted;
        
        private System.Threading.SendOrPostCallback earning_pointOperationCompleted;
        
        private System.Threading.SendOrPostCallback redeem_pointOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancel_redeem_pointOperationCompleted;
        
        private System.Threading.SendOrPostCallback redeem_stampsOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancel_redeem_stampsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public service2() {
            this.Url = global::MyPoinNew_CoreGateway.Properties.Settings.Default.MyPoinNew_CoreGateway_MyPoinCore_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckPoinCompletedEventHandler CheckPoinCompleted;
        
        /// <remarks/>
        public event earning_pointCompletedEventHandler earning_pointCompleted;
        
        /// <remarks/>
        public event redeem_pointCompletedEventHandler redeem_pointCompleted;
        
        /// <remarks/>
        public event cancel_redeem_pointCompletedEventHandler cancel_redeem_pointCompleted;
        
        /// <remarks/>
        public event redeem_stampsCompletedEventHandler redeem_stampsCompleted;
        
        /// <remarks/>
        public event cancel_redeem_stampsCompletedEventHandler cancel_redeem_stampsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckPoin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] CheckPoin(string json) {
            object[] results = this.Invoke("CheckPoin", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void CheckPoinAsync(string json) {
            this.CheckPoinAsync(json, null);
        }
        
        /// <remarks/>
        public void CheckPoinAsync(string json, object userState) {
            if ((this.CheckPoinOperationCompleted == null)) {
                this.CheckPoinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPoinOperationCompleted);
            }
            this.InvokeAsync("CheckPoin", new object[] {
                        json}, this.CheckPoinOperationCompleted, userState);
        }
        
        private void OnCheckPoinOperationCompleted(object arg) {
            if ((this.CheckPoinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPoinCompleted(this, new CheckPoinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/earning_point", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] earning_point(string json) {
            object[] results = this.Invoke("earning_point", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void earning_pointAsync(string json) {
            this.earning_pointAsync(json, null);
        }
        
        /// <remarks/>
        public void earning_pointAsync(string json, object userState) {
            if ((this.earning_pointOperationCompleted == null)) {
                this.earning_pointOperationCompleted = new System.Threading.SendOrPostCallback(this.Onearning_pointOperationCompleted);
            }
            this.InvokeAsync("earning_point", new object[] {
                        json}, this.earning_pointOperationCompleted, userState);
        }
        
        private void Onearning_pointOperationCompleted(object arg) {
            if ((this.earning_pointCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.earning_pointCompleted(this, new earning_pointCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/redeem_point", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] redeem_point(string json) {
            object[] results = this.Invoke("redeem_point", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void redeem_pointAsync(string json) {
            this.redeem_pointAsync(json, null);
        }
        
        /// <remarks/>
        public void redeem_pointAsync(string json, object userState) {
            if ((this.redeem_pointOperationCompleted == null)) {
                this.redeem_pointOperationCompleted = new System.Threading.SendOrPostCallback(this.Onredeem_pointOperationCompleted);
            }
            this.InvokeAsync("redeem_point", new object[] {
                        json}, this.redeem_pointOperationCompleted, userState);
        }
        
        private void Onredeem_pointOperationCompleted(object arg) {
            if ((this.redeem_pointCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.redeem_pointCompleted(this, new redeem_pointCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancel_redeem_point", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] cancel_redeem_point(string json) {
            object[] results = this.Invoke("cancel_redeem_point", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void cancel_redeem_pointAsync(string json) {
            this.cancel_redeem_pointAsync(json, null);
        }
        
        /// <remarks/>
        public void cancel_redeem_pointAsync(string json, object userState) {
            if ((this.cancel_redeem_pointOperationCompleted == null)) {
                this.cancel_redeem_pointOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancel_redeem_pointOperationCompleted);
            }
            this.InvokeAsync("cancel_redeem_point", new object[] {
                        json}, this.cancel_redeem_pointOperationCompleted, userState);
        }
        
        private void Oncancel_redeem_pointOperationCompleted(object arg) {
            if ((this.cancel_redeem_pointCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancel_redeem_pointCompleted(this, new cancel_redeem_pointCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/redeem_stamps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] redeem_stamps(string json) {
            object[] results = this.Invoke("redeem_stamps", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void redeem_stampsAsync(string json) {
            this.redeem_stampsAsync(json, null);
        }
        
        /// <remarks/>
        public void redeem_stampsAsync(string json, object userState) {
            if ((this.redeem_stampsOperationCompleted == null)) {
                this.redeem_stampsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onredeem_stampsOperationCompleted);
            }
            this.InvokeAsync("redeem_stamps", new object[] {
                        json}, this.redeem_stampsOperationCompleted, userState);
        }
        
        private void Onredeem_stampsOperationCompleted(object arg) {
            if ((this.redeem_stampsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.redeem_stampsCompleted(this, new redeem_stampsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/cancel_redeem_stamps", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] cancel_redeem_stamps(string json) {
            object[] results = this.Invoke("cancel_redeem_stamps", new object[] {
                        json});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void cancel_redeem_stampsAsync(string json) {
            this.cancel_redeem_stampsAsync(json, null);
        }
        
        /// <remarks/>
        public void cancel_redeem_stampsAsync(string json, object userState) {
            if ((this.cancel_redeem_stampsOperationCompleted == null)) {
                this.cancel_redeem_stampsOperationCompleted = new System.Threading.SendOrPostCallback(this.Oncancel_redeem_stampsOperationCompleted);
            }
            this.InvokeAsync("cancel_redeem_stamps", new object[] {
                        json}, this.cancel_redeem_stampsOperationCompleted, userState);
        }
        
        private void Oncancel_redeem_stampsOperationCompleted(object arg) {
            if ((this.cancel_redeem_stampsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancel_redeem_stampsCompleted(this, new cancel_redeem_stampsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CheckPoinCompletedEventHandler(object sender, CheckPoinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPoinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPoinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void earning_pointCompletedEventHandler(object sender, earning_pointCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class earning_pointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal earning_pointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void redeem_pointCompletedEventHandler(object sender, redeem_pointCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class redeem_pointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal redeem_pointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void cancel_redeem_pointCompletedEventHandler(object sender, cancel_redeem_pointCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancel_redeem_pointCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancel_redeem_pointCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void redeem_stampsCompletedEventHandler(object sender, redeem_stampsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class redeem_stampsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal redeem_stampsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void cancel_redeem_stampsCompletedEventHandler(object sender, cancel_redeem_stampsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancel_redeem_stampsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancel_redeem_stampsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591